# Generated by Django 3.0.6 on 2020-07-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_num', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=2)),
                ('grade_letter', models.CharField(max_length=1, null=True)),
                ('motto', models.TextField(blank=True, default=None, error_messages={'unique': 'Bunday shior allaqachon mavjud!'}, max_length=200, null=True, unique=True, verbose_name='Shior')),
            ],
            options={
                'unique_together': {('grade_num', 'grade_letter')},
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.DateField(null=True, verbose_name='yy-mm-dd')),
                ('nation', models.CharField(max_length=100, null=True, verbose_name='Millati')),
                ('m_name', models.CharField(max_length=200, null=True, verbose_name="Mother's name")),
                ('m_surname', models.CharField(max_length=200, null=True, verbose_name="Mother's surname")),
                ('f_surname', models.CharField(max_length=200, null=True, verbose_name="Father's surname")),
                ('f_name', models.CharField(max_length=200, null=True, verbose_name="Father's name")),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='full_crud.Grade')),
            ],
            options={
                'unique_together': {('first_name', 'date_of_birth', 'surname', 'nation', 'grade', 'm_name', 'm_surname', 'f_name', 'f_surname')},
            },
        ),
    ]
