# Generated by Django 3.0.6 on 2020-07-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('full_crud', '0002_auto_20200721_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_crud.GradeNum'),
        ),
    ]
